create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
create table ingredients (id bigint not null auto_increment, quantity double precision, serving varchar(255), product_id bigint, meal_id bigint, primary key (id)) engine=InnoDB;
create table meals (meal_id bigint not null auto_increment, name varchar(255), recipe varchar(255), primary key (meal_id)) engine=InnoDB;
create table nutrients (calories double precision, carbohydrates double precision, fat double precision, protein double precision, sugars double precision, product_id bigint not null, primary key (product_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, name varchar(255), primary key (product_id)) engine=InnoDB;
alter table ingredients add constraint FK34jbb91wprx6ys2443vf43cxj foreign key (product_id) references products (product_id);
alter table ingredients add constraint FKi0yf0d5o7g8fx3y80avay8o3l foreign key (meal_id) references meals (meal_id);
alter table nutrients add constraint FKhmk0ymlva2pr10cb0d44eas17 foreign key (product_id) references products (product_id);
